baseURL: https://blog.sidpatel.org/ 
languageCode: en-us
title: Exploring CS
paginate: 5
theme: "PaperMod"

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Blog Posts 
                  url: archives  
                  weight: 4
                - name: Search
                  url: search/
                  weight: 15  
                - name: Categories
                  url: categories/
                  weight: 10

taxonomies:
    category: categories
    tag: tags
    series: series

params:
    env: production
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 100
        threshold: 0.6
        keys: ["title", "content", "categories"]
    cover:
        responsiveImages: false
        hiddenInList: true
    # defaultTheme: light
    # defaultTheme: dark
    defaultTheme: dark # to switch between dark or light according to browser theme
    disableThemeToggle: false

    # This will show share button on the post
    ShowShareButtons: true

    # This will show the post read time on the page
    ShowReadingTime: true
    # This will show Previous / Next post suggestion under a single post
    ShowPostNavLinks: true
    # This will Adds BreadCrumb Navigation above Post’s Title to show subsections and Navigation to Home
    ShowBreadCrumbs: true
    # This will show the authors on the posts
    author: Siddharth Patel

    # This will enable the comments
    comments: true

    homeInfoParams:
      Title: Hi there 👋 !!
      Content: >
       &nbsp;  

       ![name](/images/profile-pic.png#center)

       &nbsp;  

       My name is Siddharth Patel and I am a Software Developer with background in Mechanical and Industrial Engineering.   

       I have created this blog *__Exploring CS__* to share various Computer Science and Software related concepts in easy to understand fashion.   
       
       My hope is to offer you different perspective on various Software related topics , and during this process, I would like to learn from you as well !   
       
       Please feel free to make suggestions on the posts via comments or reach me via links mentioned below.  
    

    socialIcons: # optional
      - name: github
        url: https://github.com/sidpatel93 
      - name: linkedin
        url: https://www.linkedin.com/in/patel-sid
      - name: email
        url: mailto:sid-patel@outlook.com
    

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

