baseURL: https://blog.sidpatel.net/ 
languageCode: en-us
title: Exploring CS
paginate: 5
theme: "PaperMod"
googleAnalytics: "G-T72REH2SJ7"

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: About Me 
                  url: /  
                  weight: 3
                - name: Blog Posts 
                  url: /posts/
                  weight: 4
                - name: Search
                  url: search/
                  weight: 15  
                - name: Categories
                  url: categories/
                  weight: 10
                - name: Portfolio
                  url: /portfolios/
                  weight: 6
                

taxonomies:
    category: categories
    tag: tags
    series: series

params:

    env: production

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 100
        threshold: 0.6
        keys: ["title", "content", "categories"]

    # analytics:
    # google:
    #     SiteVerificationTag: "G-T72REH2SJ7"

    cover:
        responsiveImages: false
        hiddenInList: true
        hiddenInSinglePage: true
    # defaultTheme: light
    # defaultTheme: dark
    defaultTheme: dark # to switch between dark or light according to browser theme
    disableThemeToggle: false

    # This will show share button on the post
    ShowShareButtons: true

    # This will show the post read time on the page
    ShowReadingTime: true
    # This will show Previous / Next post suggestion under a single post
    ShowPostNavLinks: true
    # This will Adds BreadCrumb Navigation above Post’s Title to show subsections and Navigation to Home
    ShowBreadCrumbs: true
    # This will show the authors on the posts
    author: Siddharth Patel

    # This will enable the comments
    comments: true

    homeInfoParams:
      Title: Hi there 👋 !!
      Content: >
       &nbsp;  

       ![name](/images/profile-pic.png#center)
       
       &nbsp;  

       My name is **Siddharth Patel** and I am a Software Developer with background in Mechanical and Industrial Engineering.  

       &nbsp;  

       I have created this blog *__Exploring CS__* to share various Computer Science and Software related concepts in easy to understand fashion. My hope is to offer you different perspective on various Software related topics , and during this process, I would like to learn from you as well !   
       
       Please feel free to make suggestions on the posts via comments or reach me via links mentioned below.  

       &nbsp;  

       ### You can download my resume here. [📥](/images/Siddharth_Resume.pdf) 

    socialIcons: # optional
      - name: github
        url: https://github.com/sidpatel93 
      - name: linkedin
        url: https://www.linkedin.com/in/patel-sid
      - name: email
        url: mailto:sid-patel@outlook.com

    profileMode:
        enabled: false
        title: Hi there 👋 !!   # optional default will be site title
        subtitle: >
          &nbsp;  

          My name is Siddharth Patel and I am a Software Developer with background in Mechanical and Industrial Engineering.
          I have created this blog *__Exploring CS__* to share various Computer Science and Software related concepts in easy to understand fashion.
          My hope is to offer you different perspective on various Software related topics , and during this process, I would like to learn from you as well !
          Please feel free to make any suggestions on the posts via comments or reach me via links mentioned below.  

          You can download my resume here. [📥](/images/Siddharth_Resume.pdf) 

        imageUrl: /images/profile-pic.png#center # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        # buttons:
        #     - name: Archive
        #       url: "/archive"
        #     - name: Github
        #       url: "https://github.com/"

        socialIcons: # optional
          - name: github
            url: https://github.com/sidpatel93 
          - name: linkedin
            url: https://www.linkedin.com/in/patel-sid
          - name: email
            url: mailto:sid-patel@outlook.com
        

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

pygmentsUseClasses: true
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false


