baseURL: https://sidpatel93.github.io/myBlog/ 
languageCode: en-us
title: Exploring CS
paginate: 5
theme: "PaperMod"

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Blog Posts 
                  url: archives  
                  weight: 4
                - name: Search
                  url: search/
                  weight: 15  

params:
    env: production
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        keys: ["title", "content"]
    # defaultTheme: light
    # defaultTheme: dark
    defaultTheme: dark # to switch between dark or light according to browser theme
    disableThemeToggle: true

    # This will show share button on the post
    ShowShareButtons: true

    # This will show the post read time on the page
    ShowReadingTime: true
    # This will show Previous / Next post suggestion under a single post
    ShowPostNavLinks: true
    # This will Adds BreadCrumb Navigation above Post’s Title to show subsections and Navigation to Home
    ShowBreadCrumbs: true
    # This will show the authors on the posts
    author: Siddharth Patel

    # This will enable the comments
    comments: true

    homeInfoParams:
      Title: Hi there !!
      Content: >
       

       ![name](static/profile-pic.png#center) 

       &nbsp

       My name is Siddharth Patel and I am a graduate student in Computer Science at Georgia Institute of Technology. However, I am also a Mechanical Engineer with 

       Bachelor's degree in Mechatronics Engineering and a Master's in Industrial Engineering. I guess the learning never stops right ??!!   

    socialIcons: # optional
      - name: github
        url: https://github.com/sidpatel93 
      - name: linkedin
        url: https://www.linkedin.com/in/patel-sid
      - name: email
        url: mailto:sid-patel@outlook.com
    

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

